{{- $podNodeSelector := include "rosecape.podNodeSelector" (dict "Release" .Release "Values" .Values "nodeSelector" .Values.nodeSelector) }}
{{- $podAffinity := include "rosecape.podAffinity" (dict "Release" .Release "Values" .Values "affinity" .Values.affinity) }}
{{- $podTolerations := include "rosecape.podTolerations" (dict "Release" .Release "Values" .Values "tolerations" .Values.tolerations) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-iceberg-rest-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      {{- if $podNodeSelector }}
      nodeSelector:
        {{- $podNodeSelector | nindent 8 }}
      {{- end }}
      {{- if $podAffinity }}
      affinity:
        {{- $podAffinity | nindent 8 }}
      {{- end }}
      {{- if $podTolerations }}
      tolerations:
        {{- $podTolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: iceberg-rest-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- include "standard_iceberg_rest_environment" . | indent 10 }}
            {{- if eq .Values.storage "adls" }}
            {{- include "azure_environment" . | indent 10 }}
            {{- end }}
            {{- if eq .Values.storage "s3" }}
            {{- include "aws_environment" . | indent 10 }}
            {{- end }}

          # if requests or limits are set\
          resources:
            {{- if .Values.resources.requests }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            {{- end }}